### ISSUE TITLE
Provide unique key to mapped Transporter array

### ISSUE THREAD

**Issue by dpgraham4401** [USEPA/haztrak#620]
# :bug: Bug Report

Currently we use the transporter's EPA ID number a 'unique' key for react to display to the array of transporters on a manifest. 9 times out of 10 that's probably fine, however when the transporter is present on the manifest more than once, it will cause problem when React tries to update and/or re-render the UI. 

We previously just used the order, however we implemented transitions via the [auto-animate](https://github.com/formkit/auto-animate) library which is why this problem is bubbling to the surface now.

**Comment by sheckathorne** [comment]
I'm checking out this issue right now. I'm wondering if it is expected behavior that the details for all like-transporters expand when clicking "Details" in the TransporterRowAction like this?:

<img width="1208" alt="Screenshot 2024-05-28 at 10 25 50 PM" src="https://github.com/USEPA/haztrak/assets/21269876/eb5f6a18-80e2-492d-98df-6a95a5f83273">

I've found a solution to sort/accordion/delete individual table records even when transporters are duplicated on the manifest, happy to create a PR if you like.
